default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development5
  username: sensei
  password: sensei1
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_test5
  username: sensei
  password: sensei1
  host: localhost
  port: 5432
